[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E","F","I","UP","B","SIM"]
ignore = []

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
strict = true
